package Integrations::EastHerts::Base;

# Generated by SOAP::Lite (v0.715) for Perl -- soaplite.com
# Copyright (C) 2000-2006 Paul Kulchenko, Byrne Reese
# -- generated at [Fri Jul  8 14:06:41 2016]
# -- generated from http://62.232.23.238:8098/soap
my %methods = (
'GetJobStatusByExternalReferences' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetJobStatusByExternalReferences',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'ExternalReferences', type => 'ro:StringArray', attr => {}),
    ], # end parameters
  }, # end GetJobStatusByExternalReferences
'GetJobsChanged' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetJobsChanged',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'ChangesSince', type => 'xs:dateTime', attr => {}),
      SOAP::Data->new(name => 'IncludeBackOfficeCreatedJobs', type => 'xs:boolean', attr => {}),
      SOAP::Data->new(name => 'OnlyStatusChanges', type => 'xs:boolean', attr => {}),
    ], # end parameters
  }, # end GetJobsChanged
'GetStreetByStreetID' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetStreetByStreetID',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'StreetID', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'InventoryTypeCount', type => 'xs:string', attr => {}),
    ], # end parameters
  }, # end GetStreetByStreetID
'GetAdaptorVersion' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetAdaptorVersion',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
    ], # end parameters
  }, # end GetAdaptorVersion
'GetStreets' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetStreets',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'PartialStreet', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'PartialLocalityOrTown', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'RecordsToReturn', type => 'xs:int', attr => {}),
      SOAP::Data->new(name => 'StartFromRecord', type => 'xs:int', attr => {}),
      SOAP::Data->new(name => 'IncludeClosedStreets', type => 'xs:boolean', attr => {}),
      SOAP::Data->new(name => 'StreetReferenceTypeFilter', type => 'ro:StreetReferenceTypeFilterEnum', attr => {}),
      SOAP::Data->new(name => 'InventoryTypeCount', type => 'xs:string', attr => {}),
    ], # end parameters
  }, # end GetStreets
'GetMap' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetMap',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'MapRequest', type => 'ro:MapRequestStructure', attr => {}),
    ], # end parameters
  }, # end GetMap
'GetJobStatusByJobNumbers' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetJobStatusByJobNumbers',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'JobNumbers', type => 'ro:StringArray', attr => {}),
    ], # end parameters
  }, # end GetJobStatusByJobNumbers
'AddCallerToJob' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#AddCallerToJob',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'JobNumber', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'Caller', type => 'ro:CallerStructure', attr => {}),
    ], # end parameters
  }, # end AddCallerToJob
'GetStreetByUniqueStreetReferenceNumber' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetStreetByUniqueStreetReferenceNumber',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'UniqueStreetReferenceNumber', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'InventoryTypeCount', type => 'xs:string', attr => {}),
    ], # end parameters
  }, # end GetStreetByUniqueStreetReferenceNumber
'UpdateCallerFeedback' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#UpdateCallerFeedback',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'ExternalReference', type => 'xs:string', attr => {}),
      SOAP::Data->new(name => 'Resolved', type => 'xs:boolean', attr => {}),
      SOAP::Data->new(name => 'Feedback', type => 'ro:CallerFeedbackArray', attr => {}),
    ], # end parameters
  }, # end UpdateCallerFeedback
'GetLinkedJobsByJobNumber' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetLinkedJobsByJobNumber',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'JobNumber', type => 'xs:string', attr => {}),
    ], # end parameters
  }, # end GetLinkedJobsByJobNumber
'UpdateJob' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#UpdateJob',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'UpdateStructure', type => 'ro:UpdateJobStructure', attr => {}),
    ], # end parameters
  }, # end UpdateJob
'GetDescriptions' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetDescriptions',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
    ], # end parameters
  }, # end GetDescriptions
'GetLinkedJobsByExternalReference' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetLinkedJobsByExternalReference',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
      SOAP::Data->new(name => 'ExternalReference', type => 'xs:string', attr => {}),
    ], # end parameters
  }, # end GetLinkedJobsByExternalReference
'GetLookups' => {
    endpoint => 'http://62.232.23.238:8098/soap',
    soapaction => 'urn:HighwaysLibrary-BaseService#GetLookups',
    namespace => 'urn:HighwaysLibrary-BaseService',
    parameters => [
    ], # end parameters
  }, # end GetLookups
); # end my %methods

use SOAP::Lite;
use Exporter;
use Carp ();

use vars qw(@ISA $AUTOLOAD @EXPORT_OK %EXPORT_TAGS);
@ISA = qw(Exporter SOAP::Lite);
@EXPORT_OK = (keys %methods);
%EXPORT_TAGS = ('all' => [@EXPORT_OK]);

sub _call {
    my ($self, $method) = (shift, shift);
    my $name = UNIVERSAL::isa($method => 'SOAP::Data') ? $method->name : $method;
    my %method = %{$methods{$name}};
    $self->proxy($method{endpoint} || Carp::croak "No server address (proxy) specified")
        unless $self->proxy;
    my @templates = @{$method{parameters}};
    my @parameters = ();
    foreach my $param (@_) {
        if (@templates) {
            my $template = shift @templates;
            my ($prefix,$typename) = SOAP::Utils::splitqname($template->type);
            my $method = 'as_'.$typename;
            # TODO - if can('as_'.$typename) {...}
            my $result = $self->serializer->$method($param, $template->name, $template->type, $template->attr);
            push(@parameters, $template->value($result->[2]));
        }
        else {
            push(@parameters, $param);
        }
    }
    $self->endpoint($method{endpoint})
       ->ns($method{namespace})
       ->on_action(sub{qq!"$method{soapaction}"!});
  $self->serializer->register_ns("urn:HighwaysLibrary","ro");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/mime/","mime");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/wsdl/soap/","soap");
  $self->serializer->register_ns("http://www.w3.org/2001/XMLSchema","xs");
  $self->serializer->register_ns("http://schemas.xmlsoap.org/soap/encoding/","soapenc");
  $self->serializer->register_ns("http://tempuri.org/","tns");
    my $som = $self->SUPER::call($method => @parameters);
    if ($self->want_som) {
        return $som;
    }
    UNIVERSAL::isa($som => 'SOAP::SOM') ? wantarray ? $som->paramsall : $som->result : $som;
}

sub BEGIN {
    no strict 'refs';
    for my $method (qw(want_som)) {
        my $field = '_' . $method;
        *$method = sub {
            my $self = shift->new;
            @_ ? ($self->{$field} = shift, return $self) : return $self->{$field};
        }
    }
}
no strict 'refs';
for my $method (@EXPORT_OK) {
    my %method = %{$methods{$method}};
    *$method = sub {
        my $self = UNIVERSAL::isa($_[0] => __PACKAGE__)
            ? ref $_[0]
                ? shift # OBJECT
                # CLASS, either get self or create new and assign to self
                : (shift->self || __PACKAGE__->self(__PACKAGE__->new))
            # function call, either get self or create new and assign to self
            : (__PACKAGE__->self || __PACKAGE__->self(__PACKAGE__->new));
        $self->_call($method, @_);
    }
}

sub AUTOLOAD {
    my $method = substr($AUTOLOAD, rindex($AUTOLOAD, '::') + 2);
    return if $method eq 'DESTROY' || $method eq 'want_som';
    die "Unrecognized method '$method'. List of available method(s): @EXPORT_OK\n";
}

1;
